config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'

  resource :dashboard, only: [:show]

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:create]
  end

  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show, :edit, :update] do
      resources :sections, only: [:create]
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show, :edit, :update]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  def edit
  end

  def update
    current_course.update_attributes(course_params)
    if current_course.valid?
      redirect_to instructor_course_path(current_course)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :image, :cost)
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
  before_action :require_authorized_for_current_lesson, only: [:update]

  #def new removed as method implememnted from courses page

  def create
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render plain: 'updated!'
  end

  private

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

  #def new removed as a result of adding modal to course page

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def update
    current_section.update_attributes(section_params)
    render plain: 'updated!'
  end

  private

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_course
  # If :course_id parameters exist in the URI, use them; otherwise default to the course listed in the section
  def current_course
    if params[:course_id]
      @current_course ||= Course.find(params[:course_id])
    else
      current_section.course
    end
  end

  def current_section
    @current_section ||= Section.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/_new_course_input_errors.html.erb
<div class="data-submit-error">
  <%= pluralize(@course.errors.count, "error") %> prevented this course from being added:
  <ul>
    <% @course.errors.full_messages.each do |msg| %>
    <li>
      <%= msg %>
    </li>
    <% end %>
  </ul>
</div>

app/views/instructor/courses/edit.html.erb
<div class="container bg-gold">
  <div class="col-10 offset-1">
    <br />
    <h2>Add a New Course</h2>
    <%= simple_form_for current_course, url: instructor_course_path(current_course) do |f| %>

      <% if current_course.errors.any? %>
        <%= render 'new_course_input_errors' %>
      <% end %>

      <%= f.input :title, error: "!" %>
      <%= f.input :description, error: "!" %>
      <%= f.input :image %>
      <%= f.input :cost, error: "!" %>
      <br />
      <%= f.submit 'Edit Course', class: 'btn bg-button' %>
      <br />
    <% end %>
    <br />
  </div>
</div>

app/views/instructor/courses/new.html.erb
<div class="container bg-gold">
  <div class="col-10 offset-1">
    <br />
    <h2>Add a New Course</h2>
    <%= simple_form_for @course, url: instructor_courses_path do |f| %>

      <% if @course.errors.any? %>
        <%= render 'new_course_input_errors' %>
      <% end %>

      <%= f.input :title, error: "!" %>
      <%= f.input :description, error: "!" %>
      <%= f.input :image %>
      <%= f.input :cost, error: "!" %>
      <br />
      <%= f.submit 'Add Course', class: 'btn bg-button' %>
      <br />
    <% end %>
    <br />
  </div>
</div>

app/views/instructor/courses/show.html.erb
<div class="container bg-gold">
  <div class="col-10 offset-1 expand-width-on-mobile">
    <br />
    <pre class="text-center">Instructor View</pre>
    <span class="badge badge-pill badge-success"><%= link_to 'Student View', course_path(current_course), class: 'bg-black' %></span>
    <span class="badge badge-pill badge-danger"><%= link_to 'Edit Course', edit_instructor_course_path(current_course), class: 'bg-black' %></span>
    <h2 class="text-center">
      <%= current_course.title %>
    </h2>

    <div class="row">
      <div class="col-12 col-md-4">
        <%= image_tag current_course.image, class: 'img-fluid margin-below-course-image course-image-border-shadow' %>
      </div>
      <div class="col-12 col-md-8">
        <%= current_course.description %>
        <span class="badge badge-pill badge-default"><%= "#{number_to_currency current_course.cost}" %></span>
      </div>
    </div>

    <div class="add-section">
      <!-- NEW SECTION Button trigger modal -->
      <button type="button" class="btn btn-course" data-toggle="modal" data-target="#newSectionModal">
        Add Section
      </button>
    </div>

    <br />

    <ul class="no-ul-padding sections">
      <!-- <div class="row"> -->
      <% current_course.sections.rank(:row_order).each do |section| %>
      <!-- <div class="col-12"> -->
      <!-- More explicit update-section-url to avoid confusion with lessons after uglify -->
        <li data-update-section-url="<%= instructor_section_path(section) %>" class="section-borders">
          <span class="fa fa-ellipsis-v sectiondrag"></span>
          <h3 class="text-center">
            <%= section.title %>
            <!-- NEW LESSON Button trigger modal -->
            <button type="button" class="btn btn-sm bg-button h6 new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
              + Lesson
            </button>
            <!-- END Button -->
          </h3>
          <ol class="lessons">
            <!-- More explicit update-lesson-url to avoid confusion with sections after uglify -->
            <% section.lessons.rank(:row_order).each do |lesson| %>
              <li data-update-lesson-url="<%= instructor_lesson_path(lesson) %>" class="lesson height-for-sorting">
                <span class="fa fa-ellipsis-v lessondrag"></span>
                <b><%= lesson.title %></b>
                <hr />
                <%= lesson.subtitle %>
              </li>
            <% end %>
          </ol>
          <br class="clr" />
        </li>
      <% end %>
    </ul>

  </div>

  <br />

</div>


<!-- Section Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="newSectionModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newSectionModalLabel">Add a Section to <%= current_course.title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |section| %>
        <div class="modal-body">
          <%= section.input :title %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <%= section.submit 'Add Section', class: 'btn bg-button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Lesson Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="newLessonModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newLessonModalLabel">Add a Lesson</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @lesson, url: "#", html: {id: 'newLessonForm' } do |lesson| %>
        <div class="modal-body">
          <%= lesson.input :title %>
          <%= lesson.input :subtitle %>
          <%= lesson.input :video %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <%= lesson.submit 'Add Lesson', class: 'btn bg-button' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(function() {
    $('.sections').sortable( {
      placeholder: 'sortable-section-placeholder',
      update: function( event, ui ) {
        $.ajax( {
          type: 'PUT',
          url: ui.item.data('update-section-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        } );
      }
    } );
  } );

  $(function() {
    $('.lessons').sortable( {
      placeholder: 'sortable-lesson-placeholder',
      update: function( event, ui ) {
        $.ajax( {
          type: 'PUT',
          url: ui.item.data('update-lesson-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        } );
      }
    } );
  } );

  $(function() {
    $('.new-lesson-button').click(function( event ) {
      var lessonUrl = $( event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    });

  });
</script>