config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'

  resource :dashboard, only: [:show]

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:create]
  end

  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show, :edit, :update] do
      resources :sections, only: [:create]
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show, :edit, :update]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  def edit
  end

  def update
    current_course.update_attributes(course_params)
    if current_course.valid?
      redirect_to instructor_course_path(current_course)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :image, :cost)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/views/courses/index.html.erb
<div class="container bg-gold">
  <div class="col-10 offset-1 expand-width-on-mobile">
    <br />
    <h2 class="text-center">Welcome to the Journey</h2>
    <p class="text-center">Please select a course below:</p>
    <% @courses.each do |course| %>
      <h3 class="course-title-centeronsmall">
        <%= link_to course.title, course_path(course), class: 'course-title' %>
      </h3>
      <div class="row">
        <div class="col-sm-4 col-12 text-center">

          <%= link_to course_path(course) do %>
          <div>
            <%= image_tag course.image, class: 'img-fluid course-image-border-shadow margin-below-course-image' %>
            <% if course.image.present? %>
              <h4 class="on-small-image-overlay">
                <span>
                  <% if course.cost == 0 %>
                    FREE
                  <% else %>
                    <%= "#{number_to_currency course.cost}" %>
                  <% end %>
                </span>
              </h4>
            <% end %>
          </div>
          <button class="btn btn-course btn-large">Details</button>
          <!-- <%= link_to 'Details', course_path(course), class: 'btn btn-course btn-large' %> -->

          <% end %>

        </div>
        <div class="col-sm-8 col-12">
          <%= course.description %>
          <span class="badge badge-pill badge-default hide-badge-under575">
<!-- Condition to display FREE or course.cost -->
          <% if course.cost == 0 %>
            FREE
          <% else %>
            <%= "#{number_to_currency course.cost}" %>
          <% end %>
<!-- END Condition -->
          </span>
        </div>
      </div>
      <hr />
      <div class="clr"></div>
    <% end %>
    <br />
  </div>
</div>

app/views/courses/show.html.erb
<div class="container bg-gold">
  <div class="col-10 offset-1 expand-width-on-mobile">
    <br />
    <div>
      <%= link_to '&laquo; Back to Courses'.html_safe, courses_path, class: 'bg-black' %>
    </div>
    <br />
    <h2 class="text-center">
      <%= @course.title %>
    </h2>
    <div class="row">
      <div class="col-sm-4 col-12 text-center">
        <%= image_tag @course.image, class: 'img-fluid course-image-border-shadow margin-below-course-image' %>
      </div>
      <div class="col-sm-8 col-12">
        <%= @course.description %>
        <span class="badge badge-pill badge-default">
          <% if @course.cost == 0 %>
            FREE
          <% else %>
            <%= "#{number_to_currency @course.cost}" %>
          <% end %>
        </span>

        <div class="bg-black">
<!-- Condition for instructor page access -->
          <% if current_user && current_user == @course.user %>
          <span class="badge badge-pill badge-success">
          <%= link_to 'Course Admin', instructor_course_path(@course) %>
          </span>
          <% end %>
<!-- END condition -->
        </div>
      </div>

      <div class="col-12 text-center">
        <% if current_user %>
          <% if current_user.enrolled_in?(@course) %>
            <h3 class="course-page-enrolled">You Are Enrolled!</h3>
          <% else %>
            <% if @course.free? %>
              <%= link_to 'Enroll For Free!', course_enrollments_path(@course), class: 'btn btn-large btn-enroll', method: :post %>
            <% else %>
              <%= form_tag course_enrollments_path(@course) do %>
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-email="<%= current_user.email %>"
                data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
                data-amount="<%= (@course.cost * 100).to_i %>"
                data-locale="auto">
                </script>
              <% end %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to 'Sign In to Enroll', new_user_session_path, class: 'btn btn-large btn-enroll' %>
        <% end %>
      </div>

    </div>

    <div class="col-12 flush-padding-with-title">
      <% @course.sections.rank(:row_order).each do |section| %>
        <div class="section-borders">
          <h3 class="text-center">
            <%= section.title %>
          </h3>
          <div class="row">
            <% section.lessons.rank(:row_order).each do |lesson| %>
              <% if section.lessons.count == 1%>
                <div class="col-12">
              <% else %>
                <div class="col-12 col-lg-6">
              <% end %>
                  <div class="lesson text-center">

                    <%= link_to lesson_path(lesson) do %>
                      <b><%= lesson.title %></b>
                      <% if lesson.video.present? %>
                        <%= image_tag('video-play.png', size: '28x28', class: 'yellow-play-icon') %>
                      <% end %>
                      <hr />
                      <%= lesson.subtitle %>
                      <br />
                    <% end %>

                  </div>
                </div> <!-- this closes either DIV based on condition -->
            <% end %>
          </div>
          <br class="clr" />
        </div>
      <% end %>
    </div>
    <br />
  </div>
</div>