config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'

  resource :dashboard, only: [:show]

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: [:create]
  end

  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show, :edit, :update] do
      resources :sections, only: [:create]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user
  has_many :sections, dependent: :destroy
  has_many :enrollments, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel

  ranks :row_order, with_same: :section_id

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end

end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons, dependent: :destroy

  include RankedModel

  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses, dependent: :destroy
  has_many :enrollments, dependent: :destroy
  has_many :enrolled_courses, through: :enrollments, source: :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!

  private

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show

  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
      # Amount in cents
      @amount = (current_course.cost * 100).to_i

      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: @amount,
        description: 'Flix-Capacitor Charge',
        currency: 'usd'
      )
    end
    
    current_user.enrollments.create(course: current_course)
    redirect_to course_path(current_course)
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_path

  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: :show

  def show
  end

  private

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_for_current_course
    if !current_user.enrolled_in?(current_lesson.section.course) && (current_lesson.section.course.user != current_user)
      redirect_to course_path(current_lesson.section.course), alert: 'ENROLL NOW to begin viewing lessons.'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def careers
  end

  def privacy
  end

  def team
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_flash.html.erb
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_user_nav.html.erb
<div class="navbar-nav">
  <% if !user_signed_in? %>
    <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-item nav-link' %>
    <span class="nav-link nav-separator">/</span>
    <%= link_to 'Log In', new_user_session_path, class: 'nav-item nav-link' %>
  <% else %>
    <span class="nav-item nav-link stop-it">&laquo; <%= current_user.email.split('@')[0] %> &raquo;</span>
    <%= link_to 'My Dashboard', dashboard_path, class: 'nav-item nav-link' %></span>
    <span class="nav-link nav-separator">/</span>
    <%= link_to "Log out".html_safe, destroy_user_session_path, method: :delete, class: 'nav-item nav-link' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="http://vjs.zencdn.net/5.17.0/video-js.css" rel="stylesheet">
  </head>

  <body>

    <div id="flex-content-container">

        <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#flix-cap-toggle" aria-controls="flix-cap-toggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <%= link_to root_path do %>
          <h1 class="navbar-brand mb-0">Flix-Capacitor</h1>
          <% end %>
          <div class="collapse navbar-collapse" id="flix-cap-toggle">
            <div class="navbar-nav mr-auto">
              <%= link_to 'See All Courses', courses_path, class: 'nav-item nav-link' %>
            </div>

            <%= render 'layouts/user_nav' %>

          </div>
        </nav>

      <!-- <div class="container"> -->

        <%= render "layouts/flash" %>

        <%= yield %>

      <!-- </div> -->

    </div>

    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-md-3">
            <span class="footer-lead">Teachers</span>
            <%= link_to 'Teach a Course', new_instructor_course_path %>
            <br />
            <%= link_to 'View Dashboard', dashboard_path %>
          </div>
          <div class="col-12 col-md-3">
            <span class="footer-lead">About</span>
            <%= link_to 'Team', team_path %>
            <br />
            <%= link_to 'Careers', careers_path %>
            <br />
            <%= link_to 'Privacy Policy', privacy_path %>
          </div>
          <div class="col-12 col-md-3">
            <span class="footer-lead">Contact</span>
            <%= mail_to 'vaughn.weiss+web@gmail.com' do %>
              Vaughn Weiss
            <% end %>
            <br />
            <span class="footer-yellow">Seattle, WA</span>
          </div>
          <div class="col-12 col-md-3 social">
            <span class="footer-lead">Social</span>
            <%= link_to 'https://github.com/VonTeacher', target: '_blank' do %>
              <i class="fa fa-github fa-2x" aria-hidden="true"></i>
            <% end %>
            <%= link_to 'https://medium.com/@vaughn.weiss', target: '_blank' do %>
              <i class="fa fa-medium fa-2x" aria-hidden="true"></i>
            <% end %>
            <%= link_to 'https://twitter.com/VonTeacher', target: '_blank' do %>
              <i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <script src="http://vjs.zencdn.net/5.17.0/video.js"></script>
    <!-- If you'd like to support IE8 -->
    <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

  </body>

</html>